### ISSUE TITLE
Update URL

### ISSUE THREAD

**Issue by anb94** [kwesterman/whi-diet-response#1]
Hi,

The URL in whi-diet-response/scripts/clean_genotypes/fetch_ensembl_snps.sh is now out of date. The new url is http://ftp.ensembl.org/pub/grch37/release-93/variation/vcf/homo_sapiens/1000GENOMES-phase_3.vcf.gz

**Comment by kwesterman** [comment]
Thanks for the heads up! The link is now updated.
